print("Mix 500g of Flour, 10g Yeast and 300ml Water in a bowl.")
print("Knead the dough for 10 minutes")
print("Add 3g of Salt.")
print("Leave to Rise for 2 Hours")
print("Bake at 200 degrees C for 30 minutes.")